
project_id = "zpwuusvgaehisdnxcild"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
port = 54325

[auth.smtp]
sender_name = "fake-sender"
sender_email = "fake-sender@example.com"

[analytics]
enabled = false
port = 54327

[experimental.functions]
enabled = true

[functions.parse-schedule-file]
verify_jwt = true
