// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpwuusvgaehisdnxcild.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwd3V1c3ZnYWVoaXNkbnhjaWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDg4NDEsImV4cCI6MjA1OTY4NDg0MX0.SA9hXvxAS9-Mygv1ImWqlxGxvE0GBQrPdZbwlqz_hJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);